# Generated by Django 5.2.7 on 2025-10-14 12:02

from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    PortalSettings = apps.get_model('portal', 'PortalSettings')
    PortalSettings.objects.get_or_create(
        pk=1,
        defaults={'ocr_engine': 'ocrmypdf'},
    )


def drop_default_settings(apps, schema_editor):
    PortalSettings = apps.get_model('portal', 'PortalSettings')
    PortalSettings.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_ocrjob_detected_languages_ocrjob_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortalSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ocr_engine",
                    models.CharField(
                        choices=[("ocrmypdf", "OCRmyPDF"), ("docling", "Docling")],
                        default="ocrmypdf",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Portal settings",
            },
        ),
        migrations.RunPython(create_default_settings, drop_default_settings),
    ]
