services:
  web:
    build:
      context: .
    image: ocrsite:latest
    command: /app/entrypoint.sh
    expose:
      - "8000"
    volumes:
      - media:/app/media
      - staticfiles:/app/staticfiles
      - dbdata:/app/db.sqlite3
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG:-False}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,ocr.casianhome.org}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-change-me}
      SITE_BASE_URL: ${SITE_BASE_URL:-http://localhost:8000}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "8000:8000"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - media:/app/media:ro
      - staticfiles:/app/staticfiles:ro

volumes:
  media:
  staticfiles:
  dbdata:
