version: '3.9'

services:
  web:
    build:
      context: .
    image: ocrsite:latest
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,ocr.casianhome.org}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-change-me}
    restart: unless-stopped
